#!/usr/bin/env python3
"""Generate the checked-in FlashRLJob CRD manifest."""

from __future__ import annotations

from pathlib import Path
import sys

import yaml


REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from flashrl.platform.k8s.job import flashrljob_crd_manifest  # noqa: E402


HEADER = (
    "# This file is automatically generated by flashrl/platform/k8s/job-crd-gen.py\n"
    "# Do not edit manually.\n"
)
OUTPUT_PATH = REPO_ROOT / "flashrl/platform/k8s/job-crd.yaml"


def render_job_crd_yaml() -> str:
    """Render the deterministic CRD YAML payload with header comments."""
    body = yaml.safe_dump(
        flashrljob_crd_manifest(),
        sort_keys=False,
    )
    return f"{HEADER}{body}"


def main() -> int:
    OUTPUT_PATH.write_text(render_job_crd_yaml(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
